version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:7.0
    container_name: kliksewa-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: kliksewa_db
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - kliksewa-network

  # Redis Service
  redis:
    image: redis:7-alpine
    container_name: kliksewa-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - kliksewa-network

  # MongoDB Express (GUI untuk MongoDB - Optional)
  mongo-express:
    image: mongo-express:latest
    container_name: kliksewa-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - kliksewa-network

  # Redis Commander (GUI untuk Redis - Optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: kliksewa-redis-commander
    restart: always
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - kliksewa-network

# Volumes untuk persistent data
volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  redis_data:
    driver: local

# Network
networks:
  kliksewa-network:
    driver: bridge